---
openapi: 3.0.0
info:
   version: 1.3.0
   title: healthinfosys open api specification
   description: detailblk API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8018
     description: detailblk
tags:
- name: detailblk
paths:
   "/detailblk/{id}":
      delete:
         tags:
         -  detailblk
         description: GpDelete
         parameters:
         -  in: "path"
            description: GpDelete
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  detailblk
         description: GpGetEntityById
         parameters:
         -  in: "path"
            description: GpGetEntityById
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/detailblk/get/search":
      get:
         tags:
         -  detailblk
         description: GpSearch
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/detailblk/get/update":
      put:
         tags:
         -  detailblk
         description: GpSearchForUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/detailblk"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/detailblk":
      put:
         tags:
         -  detailblk
         description: GpUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/detailblk"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  detailblk
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  detailblk
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/detailblk"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/detailblk/userid/created_by":
      get:
         tags:
         -  detailblk
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      detailblk:
         type: object
         properties:
            unitno:
               type: "string"
               description: Description
            ndproductcode:
               type: "string"
               description: Description
            bloodgroup:
               type: "string"
               description: Description
            currentvolume:
               type: "string"
               description: Description
            volumeunits:
               type: "string"
               description: Description
            rhesuscode:
               type: "string"
               description: Description
            ndexpirydate:
               type: "string"
               description: Description
            unitstatus:
               type: "string"
               description: Description
            decodedunitstatus:
               type: "string"
               description: Description
            ndreserveddate1:
               type: "string"
               description: Description
            storageloccode:
               type: "string"
               description: Description
            ndsimunit:
               type: "string"
               description: Description
            ndselectunit:
               type: "string"
               description: Description
            ndautologunit:
               type: "string"
               description: Description
            nddirectedunit:
               type: "string"
               description: Description