---
openapi: 3.0.0
info:
   version: 1.3.0
   title: healthinfosys open api specification
   description: mirror API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8020
     description: mirror
tags:
- name: mirror
paths:
   "/mirror/{id}":
      delete:
         tags:
         -  mirror
         description: GpDelete
         parameters:
         -  in: "path"
            description: GpDelete
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  mirror
         description: GpGetEntityById
         parameters:
         -  in: "path"
            description: GpGetEntityById
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/mirror/get/search":
      get:
         tags:
         -  mirror
         description: GpSearch
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/mirror/get/update":
      put:
         tags:
         -  mirror
         description: GpSearchForUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/mirror"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/mirror":
      put:
         tags:
         -  mirror
         description: GpUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/mirror"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  mirror
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  mirror
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/mirror"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/mirror/userid/created_by":
      get:
         tags:
         -  mirror
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      mirror:
         type: object
         properties:
            viewsummary:
               type: "string"
               description: Description
            pbxmatchtest:
               type: "string"
               description: Description
            btnmulunit:
               type: "string"
               description: Description
            pbxmtch:
               type: "string"
               description: Description
            pbissue:
               type: "string"
               description: Description
            pbrevertiss:
               type: "string"
               description: Description
            pbreturn:
               type: "string"
               description: Description
            pbunitattribute:
               type: "string"
               description: Description
            pbunitantigens:
               type: "string"
               description: Description
            nddoblegend:
               type: "string"
               description: Description
            page1lov:
               type: "string"
               description: Description
            page1date:
               type: "string"
               description: Description
            ndurgent:
               type: "string"
               description: Description
            ndroutine:
               type: "string"
               description: Description
            ndautologouscolorcode:
               type: "string"
               description: Description
            ndmultiallocation:
               type: "string"
               description: Description
            pbpatantibodies:
               type: "string"
               description: Description
            pbpatrequire:
               type: "string"
               description: Description
            pushbutton328:
               type: "string"
               description: Description
            pbtransfusehist:
               type: "string"
               description: Description
            btnmotherspecdtls:
               type: "string"
               description: Description
            btntransplantdtls:
               type: "string"
               description: Description
            item404:
               type: "string"
               description: Description
            ndstat:
               type: "string"
               description: Description
            ndpatient:
               type: "string"
               description: Description
            userpopmenu:
               type: "string"
               description: Description
            item500:
               type: "string"
               description: Description
            ndselallunits:
               type: "string"
               description: Description
            barcodeunit:
               type: "string"
               description: Description
            pbfindetails:
               type: "string"
               description: Description
            ndbldprocessdisptemp:
               type: "string"
               description: Description
            pbordercomment:
               type: "string"
               description: Description
            pbaliquot:
               type: "string"
               description: Description
            pbpool:
               type: "string"
               description: Description
            ndhideline:
               type: "string"
               description: Description
            pbmodifyreservedate:
               type: "string"
               description: Description